
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ANCHOR CASES LCONTINENT LCOUNTRY LTOTALCASES LWORLD NAME RCONTINENT SKIPTOKENstart : world_cases\n                | tcases\n                | country_casesworld_cases : LTOTALCASES SKIPTOKEN CASES CASES CASES CASES CASES CASES CASES CASES CASES CASEStcases : LCONTINENT CASES NAME SKIPTOKEN CASES CASES CASES CASES CASES CASES CASEScountry_cases : LCOUNTRY NAME CASES CASES CASES CASES CASES CASES CASES CASES CASES CASES CASES CASES CASES CASES'
    
_lr_action_items = {'LTOTALCASES':([0,],[5,]),'LCONTINENT':([0,],[6,]),'LCOUNTRY':([0,],[7,]),'$end':([1,2,3,4,36,38,43,],[0,-1,-2,-3,-5,-4,-6,]),'SKIPTOKEN':([5,12,],[8,15,]),'CASES':([6,8,10,11,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,37,39,40,41,42,],[9,11,13,14,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,]),'NAME':([7,9,],[10,12,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[1,]),'world_cases':([0,],[2,]),'tcases':([0,],[3,]),'country_cases':([0,],[4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> world_cases','start',1,'p_start','yesterdayData.py',128),
  ('start -> tcases','start',1,'p_start','yesterdayData.py',129),
  ('start -> country_cases','start',1,'p_start','yesterdayData.py',130),
  ('world_cases -> LTOTALCASES SKIPTOKEN CASES CASES CASES CASES CASES CASES CASES CASES CASES CASES','world_cases',12,'p_world_cases','yesterdayData.py',134),
  ('tcases -> LCONTINENT CASES NAME SKIPTOKEN CASES CASES CASES CASES CASES CASES CASES','tcases',11,'p_tcases','yesterdayData.py',159),
  ('country_cases -> LCOUNTRY NAME CASES CASES CASES CASES CASES CASES CASES CASES CASES CASES CASES CASES CASES CASES','country_cases',16,'p_country_cases','yesterdayData.py',188),
]
